basics.lib
compressors.lib

Took a while, but here we finally are!  :)
I implemented the suggestions by @josmithiii in https://github.com/grame-cncm/faustlibraries/issues/3:
- omit the N from the names of the variants on slidingReduce
- change slidingSum to the less CPU-intensive version
- add numerically stable "forever" versions
I used the p postfix that @josmithiii  mentioned in the context of protected functions
Let me know if any more changes are needed.

add compressors

---

compressors.lib

Not sure how it happened, but the code currently in master doesn't compile; ba.bypass doesn't exist...

use ba.bypass1 instead of ba.bypass

---

oscillators.lib

Somehow a mem ended up in there, that wasn't in [the original](https://www.mail-archive.com/faudiostream-users@lists.sourceforge.net/msg00983.html).

lf_sawpos: remove mem from freq

---

oscillators.lib

This a replacement for https://github.com/grame-cncm/faustlibraries/pull/22, since that one was off my master branch, which is not handy, and I don't think it's possible to change which branch a PR uses.

Fixup quadosc

---

hoa.lib

This PR fixes the map function that generates an audio glitch when the radius of the source equals one because there is division by zero (volume) and another value (ouverture) jumps to zero.

Fix map function in hoa.lib

---

hoa.lib

This PR fixes the ho.rotate function because the signal is inverted (+/-).

fix ho.rotate function in hoa.lib

---

compressors.lib

Basic lookahead limiter based on Zmölnig / Falkner.
This function might be particularly useful for those who need a cheap limiter with low distortion, although release times may not be acceptable for all applications.

added basic lookahead limiter

---

oscillators.lib

Most original CZ oscillators output a sine wave when index=0, but that sine wave is not phase-aligned with ``fund:sin``.
This PR adds a version of those oscillators that *is* aligned.

CZ oscillators: refactor and add phase aligned versions

---

basics.lib
compressors.lib

the compressors where using:
- ba.crossfade, replaced by it.interpolate_linear
- ba.minimum, replaced by ba.parallelMin
Added ba.parallelMin as well as a generalized version and versions with
the other binary commutative operators.
I left out parallelSum, since I figured it was too basic: si.bus(n):>_

compressors: add missing functions

---

stdfaust.lib
wavedigitalfilters.lib

Added wavedigitalfilters.lib, a new library I've written for creating Wave Digital Filter (WDF) models in Faust. 
Full documentation of the library, as well as examples, can be found at:
https://github.com/droosenb/faust-wdf-library
submitted at the recommendation of Julius Smith and Romain Michon

New Wave Digital Filter Modeling Library

---

wdmodels.lib

New release of the library. 
Changelog:
Changed library syntax. All adaptor names now follow the form [prefix]_[nodeName]_[suffix]. 
-The only valid prefix for nodes is 'u' denoting an unadapted node, i.e. "u_voltage". 
-Nodes are assumed to be adapted unless otherwise noted.  The suffix denotes the adaptor's output from the model. No suffix denotes no output. 'Vout' denotes a voltage output. 'Iout' denotes a current output. 
Added genericNode functions that transform Faust functions and scattering matrices into nodes suitable for use in the library. See internal documentation for more information on use. 
Fixed typos and improved readability of documentation
Added one R-type node, 'sixportPassive' which appears in many passive EQ circuits. 
Changed internal library declaration of …

wdmodels.lib v. 0.2.0

---

compressors.lib

Some functions are not getting docs in Faust IDE due to empty lines between comments or the lack of closing string `//-----`

Update compressor.lib for better doc parsing

---

wdmodels.lib

Fixing a few parenthetical errors in wdmodels.lib that were preventing the library from compiling.

Fix typos in wdmodels.lib

---

aanl.lib

@orlarey @josmithiii @sletz
This fixes the conflicts caused by all.lib, although if we'll always need to worry about all.lib, we'll never be able to take advantage of the different environments in stdfaust.lib, will we?
I didn't know that issue so we should add a note in the library contribution section to make it clear that conflicts can be an issue even outside of the specific environment.
Best,
Dario

fix definition conflicts in aanl

---

phaflangers.lib

Fixed documentation for `phaser2_stereo` function that `phase` argument is used only for mono version.
From
```faust
_ : phaser2_stereo(Notches,phase,width,frqmin,fratio,frqmax,speed,depth,fb,invert) : _
```
To
```faust
_,_ : phaser2_stereo(Notches,width,frqmin,fratio,frqmax,speed,depth,fb,invert) : _,_
```
Maybe, a typical parameter for `fratio`  is needed. A too-large value (like 200~) causes a feedback glitch and difficult to expect what the parameter means.

Fixed documentation for stereo phasor

---

compressors.lib

Everywhere in the comments, *_FFFB_* (Feed-Forward FeedBack) is used but in the actual dsp code it is *_FBFF_*. This leads to Faust IDE incorrectly parsing the doc and suggesting an unknown bit of code for the compiler.
It would have been easier to only replace *_FBFF_* by *_FFFB_* (2 occurences) but this would have broken any project based on those definitions.

compressors.lib: typo in comments

---

compressors.lib

RMS_FBcompressor_peak_limiter_N_chan uses twice the 'meter' parameter and this leads to a duplicate definition of the corresponding UI primitive label.

compressors.lib: incorrect definition

---

wdmodels.lib

Unfortunately, the reference equation had a small typo. Going back to the derivation, we can see that the factor of two does not actually need to be there.
As an example, we can make a simple circuit with a resistive current source, resistor, and switch, all in parallel. When the switch is closed, we should expect the current going through the resistor to be equal and opposite to the current coming from the current source, so long as the resistive current source has a sufficiently large resistance. When running this code in Faust, we get an output of -2 amps, rather than -1 amps as we would expect. After making the change shown here, we get the expected result.
```faust
switch_closed = -1;
current_amps = 1.0;
model(in1) = wd.buildtree(tree)
with {
switch(i) = …
```

wdmodels: fix tiny error in resistive current source

---

compressors.lib

Keep the knee parameter in peak_compression_gain_mono and RMS_compression_gain_mono within the range [ma.EPSILON,-2*thresh]
to prevent a divide by 0 and a discontinuity in the computed gain reduction.

compressors.lib hardening

---

compressors.lib

While using boolean logic in commit 4d5668 I mistakenly forgot to remove the "+1" that was not needed anymore.

Fix error in compressors.lib

---

filters.lib

Hello, @orlarey @sletz @josmithiii @rmichon.
I'm digging into multi-band processing lately and I needed a crossover. I've implemented the popular 4th-order Linkwitz-Riley crossovers, which have a neat flat response when summing the outputs back together; I've compared them to the current filter bank that we have in the libraries and it could be a useful contribution.
See the magnitude response of the filter outputs below. The split frequencies for the 2-way, 3-way, and 4-way crossover tests are 1280; 640, 2560; 320, 1280, 5120.
Ciao,
Dario
[xover2.pdf](https://github.com/grame-cncm/faustlibraries/files/7975153/xover2.pdf)
[xover3.pdf](https://github.com/grame-cncm/faustlibraries/files/7975154/xover3.pdf)
[xover4.pdf](https://github.com/grame-cncm/faustlibraries/files/7975156/xover4.pdf)

add 2-way, 3-way, and 4-way Linkwitz-Riley fourth-order crossovers

---

signals.lib

This is just a minor change in the doc of si.vecOp to make sure that the FDN example is stable.

make FDN doc example stable

---

compressors.lib

This has 2 advantages:
- the link now works correct, since it crossfades in the dB scale
- less cpu usage when a meter is used,
because it doesn't have to go back to the dB scale

compressors: leave the GR signal in the dB scale

---

filters.lib

@sletz here we go: I added the K-filter `itu_r_bs_1770_4_kfilter` within a new section "Standardized Filters". You suggested adding the filter over here: https://github.com/trummerschlunk/master_me/issues/16#issuecomment-1214904902.
I think, there are a more standardized filters, that could be added in the future. However, please feel free to move the code, if another section or file would be more appropriate.
Does the code in this pull-request meet all the testing requirements of the FAUST libraries?

ITU-R BS.1770-4 "K-filter"

---

basics.lib

Since we are looking for the closest value below id. 
Also: d needs to be positive.

 tabulate: use int(id+0.5) in .val  (was:  tabulate: use floor(id) in the interpolators)

---

basics.lib

The double spaces at the end of a line render as a newline, so the longer blocks of text get a bit of breathing space.
I also added a bit about the unsafe ends of ranges that I adapted from Oleg.
I'm pretty sure it also applies to ``ba.tabulate``.

Even more formatting

---

compressors.lib

accidental double ba.db2linear
introduced in https://github.com/grame-cncm/faustlibraries/pull/140

fix RMS_FBcompressor_peak_limiter_N_chan

---

basics.lib

This clarifies something important...
Demo:
```faust
os = library("oscillators.lib");
it = library("interpolators.lib");
ba = library("basics.lib");
if = ba.if;
bpf = environment
{
// Start a break-point function
start(x0,y0) = \(x).(x0,y0,x,y0);
// Add a break-point
point(x1,y1) = \(x0,y0,x,y).(x1, y1, x, if(x < x0, y, if(x < x1, y0 + (x-x0)*(y1-y0)/(x1-x0), y1)));
// End a break-point function
end(x1,y1) = \(x0,y0,x,y).(if(x < x0, y, if(x < x1, y0 + (x-x0)*(y1-y0)/(x1-x0), y1)));
// Add a curve-point. `B` (compile-time constant) must be in range (0,1]
curve(B,x1,y1) = \(x0,y0,x,y).(x1, y1, x, if(x < x0, y, if(x < x1, _curve_util(x0,x1,y0,y1,B,x), y1)));
// End with a curve-point. `B` (compile-time constant) must be in range (0,1]
curve_end(B,x1,y1) = \(x0,y0,x,y).(if(x < x0, y, if(x < …
```

improve bpf curve documentation

---

basics.lib

Here is a polyphonic demo:
```faust
import("basics.lib");
//--------------------------`(ba.)downSampleCV`---------------------------
//
// A version of `ba.downSample` where the frequency parameter has
// been replaced by an `amount` parameter that is in the range zero
// to one. WARNING: this function doesn't change the rate of a
// signal, it just holds samples...
//
// #### Usage
// ```
// _ : downSampleCV(amount) : _
// ```
// Where:
//
// * `amount`: The amount of down-sampling to perform [0..1]
//-----------------------------------------------------------------------
downSampleCV(amt) = sAndH(hold)
with {
// If amt is 0, then freq should be ma.SR/2.
// If amt is 1, then freq should be 491.
// 491 is derived from listening to the Serum synthesizer.
freq = amt …
```

add ba.downSampleCV

---

demos.lib

This adds an implementation of the stereo "Reverb Tank" example from Designing audio effect plugins in C++ (2nd ed.) by Will Pirkle.

add reverbTank_demo

---

reverbs.lib

In my listening test, this improves the situation where the time parameter is about 0.25 and you sweep the size from 0 to 1. Before, large size values would take too long to decay (violating the choice of a low 0.25 time parameter). Now it seems to match the original Vital plugin better.

improve Vital reverb based on listening test

---

basics.lib

Select a bus among `NUM_BUSES` buses, where each bus has `BUS_SIZE` outputs. The order of the signal inputs should be the signals of the first bus, the signals of the second bus, and so on.
I thought that there was a need for a variation of `ba.selectmulti` where the crossfade is zero and the "circuits" are many signals from many buses.
Example program:
```faust
selectbus(BUS_SIZE, NUM_BUSES, i) = ro.interleave(BUS_SIZE, NUM_BUSES) : par(j, BUS_SIZE, ba.selectn(NUM_BUSES, i));
BUS_SIZE = 3;
NUM_BUSES = 4;
i = nentry("i", 0, 0, NUM_BUSES-1, 1);
process = si.bus(BUS_SIZE*NUM_BUSES) : selectbus(BUS_SIZE, NUM_BUSES, i);
```

add ba.selectbus

---

basics.lib

I was looking for an alternative to the ABComparaison plugin (by Danial Rudrich) and found the new selectbus function then made a version with crossfade using code from selectmulti. The name of this augmented version could be different, or it could even replace selectbus (if the overhead of computing the crossfade is not too high). This is a  draft pull request, so please let me know!
Here's some demo code:
```
bus_size = 2;
num_buses = 3;
xfade = hslider("Xfade (sec)", 0.1, 0, 1, 0.1) * ma.SR;
choice = hslider(
"Bus[style:radio{'A':1;'B':2;'C':3}]",
1, 1, num_buses, 1) -1;
process = ba.selectxbus(bus_size, num_buses, xfade, choice);
```

add selectxbus (selectbus with crossfade)

---

oscillators.lib

Change documentation from `Positive` to `Zero-Mean` for `os.lf_triangle`, since `os.lf_trianglepos` is the positive function.

Fix documentation for os.lf_triangle

---

doc/Makefile
doc/docs/standardFunctions.md
doc/mkdocs.yml
doc/scripts/faustlib2md.awk
doc/scripts/makeindex.awk
doc/theme/base.html

Improved on PR #197 
Updated Makefile to force mkdocs to a fixed version.
Updated mkdocs/theme/base.html to use jquery-3.6.0.min.js as provided by mkdocs 1.5.3
This prevents numerous errors caused by significant changes in newer mkdocs versions.
Also included are the fixes or all links in *.md documents.

Updated to mkdocs 1.5.3

---

doc/Makefile

This one is quite simple and allows correct use of the FAUSTLIBS var troughout the Makefile.

Use FAUSTLIBS var instead of a static path in SRC var definition

---

reverbs.lib

I encountered a discrepancy in the Lowpass Feedback Comb Filter within re.mono_freeverb. The filter does not compensate for the 1-sample delay introduced by the feedback in FAUST. Currently, when setting the function lbcf(dt, fb, damp), the delay in the second tap of the signal results in 2 * dt + 1 samples, instead of the expected 2 * dt samples due to the additional sample delay in the feedback path. To resolve this issue, I modified the function to delay by (dt - 1) in the feedback path, ensuring correct alignment. I also added a mem at the end of the circuit to preserve the correct delay in the feedforward path. This change ensures that the feedback delay is aligned properly, avoiding any additional unintended delay.

Fix delay compensation in Lowpass Feedback Comb Filter

---

filters.lib
linearalgebra.lib

This adds a Kalman filter.
Demo 1 (`N=1`,`M=1`) (don't listen, just use oscilloscope):
```faust
process = u, z : kalman(N, M, B, R, H, Q, F, reset) : it.interpolate_linear(filteredAmt, z)
with {
B = 1.;
R = 0.1;
H = 1;
Q = .01; 
F = la.identity(N);
reset = button("reset");
// Dimensions
N = 1; // State size
M = 1; // Measurement size
freq = hslider("Freq", 1, 0.01, 10, .01);
u = 0.; // constant input
trueState = os.osc(freq)*.5 + u;
noiseGain = hslider("Noise Gain", .1, 0, 1, .01);
filteredAmt = hslider("Filter Amount", 1, 0, 1, .01) : si.smoo;
measurementNoise = no.noise*noiseGain;
z = trueState + measurementNoise; // Observed state
};
```
Demo 2 (`N=2`, `M=1`) (don't listen, just use oscilloscope)
```faust
process = u, z : kalman(N, M, B, R, H, Q, F, reset)
with {
B = par(i, N, 0);
R = …
```

Add Kalman filter

---

filters.lib

Fixes DSP mistake in oneEuro.
Demo that outputs zero when compared with reference implementation:
```faust
oneEuro(derivativeCutoff, beta, minCutoff) = _oneEuro ~ _
with {
// exponential moving average that calculates its own alpha from a cutoff in Hz
// _ : ema(cutoff) : _
ema(cutoff) = tick ~ _
with {
alpha = 1.0 / (1.0 + ma.SR / (2 * ma.PI * cutoff));
tick(prev, x) = prev*(1-alpha) + x*alpha;
};
_oneEuro(prev, x) = x : ema(adaptiveCutoff)
with {
derivative = (x - prev)*ma.SR;
derivativeFiltered = derivative : ema(derivativeCutoff);
adaptiveCutoff =  minCutoff + beta * abs(derivativeFiltered);  
};
};
euro(min_cutoff, beta, x) = x_hat letrec {
'dx_hat = dx_hat_n;
'x_hat = expsmo(a, x, x_hat);
where
dx = (x - x_hat) / t_e;
dx_hat_n = expsmo(a_d, dx, dx_hat); …
```

fix oneEuro

---

filters.lib

I'm trying to close the PR here: https://github.com/grame-cncm/faustlibraries/pull/166
It's supposed to be the same math as in Vital's SVF functions.
https://github.com/mtytel/vital/blob/636ca0ef517a4db087a6a08a6a8a5e704e21f836/src/synthesis/filters/digital_svf.cpp#L292-L295
and
https://github.com/mtytel/vital/blob/636ca0ef517a4db087a6a08a6a8a5e704e21f836/src/synthesis/filters/digital_svf.cpp#L256C36-L263
Demo:
```faust
svf = fi.svf;
svf_morph(f, q, _b, x) = svf.lp(f,q,x)*w_LP + svf.bp(f,q,x)*w_BP + svf.hp(f,q,x)*w_HP
with {
b = _b - 1; // b is now -1 to 1.
w_LP = max(-b, 0);
w_BP = sqrt(1 - b^2);
w_HP = max(b, 0);
};
svf_notch_morph(f, q, _b, x) = svf.lp(f,q,x)*w_LP + svf.hp(f,q,x)*w_HP
with {
b = _b - 1; // b is now -1 to 1.
w_LP = min(1-b, 1);
w_HP = min(1+b, …
```

add svf morph functions

---

reverbs.lib

Initial implementation of Keith Barr's all-pass single feedback loop reverb in reverbs.lib. This version is a work in progress, as the code has been developed by interpreting the original rom_rev1.spn file from the Spin Semiconductor Free DSP Programs. Testing and adjustments are still needed to ensure proper behavior and accurate translation from the FV-1 assembly. The reverb model aims to replicate the increasing diffusion and density characteristics of the original design, supporting both mono and stereo input configurations. In mono input mode, the signal is distributed across the stereo field to create a sense of width. In stereo input mode, the signal is injected at two different points within the all-pass feedback loop.

Add Keith Barr Allpass Loop Reverb to reverbs.lib

---

filters.lib

Vicanek's decramped second-order resonant filters, which require no oversampling, although they require double-precision.

Add Vicanek's decramped second-order resonant filters

---

basics.lib
oscillators.lib
physmodels.lib

os.sidebands(), pm.rk_solve() and ba.ifNcNo() can re-use ba.pick/pickN helpers instead of
re-implementing this code by hand.
No changes in generated code.

use ba.pick/pickN helpers to  simplify os.sidebands(), pm.rk_solve() and ba.ifNcNo() 
