basics.lib, maths.lib
As discussed [here](https://github.com/grame-cncm/faust/issues/150#issuecomment-375393129)
=> small fixes for slidingReduce

physmodels.lib
I already mentioned the error and solution here: [https://github.com/grame-cncm/faust/pull/223](https://github.com/grame-cncm/faust/pull/223). Now I also wrote some documentation.
=> Fix modalModel and add documention

hoa.lib
Add 3D functions from https://github.com/CICM/HoaLibrary-Faust/blob/master/Sources/HoaEncoder3D.dsp as discussed in #18
=> Add 3D functions

oscillators.lib
Hello,
I've implemented PolyBLEP-based oscillators (sawtooth, square and triangle) in Faust. I thought the code may be useful for others, hence the pull request. I hope you like it :)
I'm not quite sure if the `polyblep` function is in the right library, but I also don't know where's better place for it.
[Here's](https://gist.github.com/Jacajack/6d54c9d8fde24ed8c02c9a964ddcf44e) some code showing the difference between sound from PolyBLEP oscillators and the oscillators currently implemented in the Faust standard library.
Thank you
=> PolyBLEP oscillators

analyzers.lib, filters.lib, maths.lib
@josmithiii Hi, Julius. I temporarily ended the names of the functions based on Zölzer's constant with "t19" as it is the time to roughly decay by 19 dB. I can change that anytime but I thought that I could first do the PR to see if all the rest looks fine.
I uploaded the libraries on the web editor and all the functions compile.
I put the averaging function in maths.lib.
Maybe pay attention to what I wrote in the description of avg_tau to be sure that it is correct.
Thanks,
Dario
=> New amp analysis

physmodels.lib
Fixe a minor typo in documentation
=> Documentation typo

physmodels.lib
Hello, this fixes a mistake found in function `pm.openStringPickUp`.
=> Fix pm.openStringPickUp

all.lib, quantizer.lib
I made a quantizer library. It takes any frequency and quantize it to a specific musical scale.
There is still some work to do (to accomodate for very low frequencies, for example) but it works fine in the current state.
=> quantizer library

basics.lib
Thanks to Oleg Nesterov for the catch and fix.
Stupidly, I had only tested with N=2.
=> fixup parallelOp

interpolators.lib
=> added fractional-index rdtable and rwtable

interpolators.lib, oscillators.lib
These generators will not lose precision over time.
Ciao,
Dario
=> better sinusoid and cosinusoid tables generators

aanl.lib
Some invisible characters might have been added with copy-pasting; it should compile now.
@sletz can you double-check?
Dario
=> fixed typos in aanl.lib

oscillators.lib
hopefully pretty self-explanatory!
=> include signals.lib in oscillators.lib fixing CZ oscillators

interpolators.lib
Hello, people.
This PR generalises the Lagrange interpolation algorithm so that arbitrary spacing of the points is supported.
The old algorithms based on uniformly spaced points are implemented as a specialisation of the generalised functions.
Ciao,
Dario
=> Extend Lagrange interpolation algorithms to support arbitrary points spacing

compressors.lib
- hardening peak_compression_gain_mono and RMS_compression_gain_mono with boolean logic for the prePost parameter
- simplification and light refactoring of most of the functions to improve readability
=> Minor improvements to compressors.lib

compressors.lib
Changed gain_computer in Peak_compression_gain_mono and RMS_compression_gain_mono for operations above 0dB
=> compressors.lib improvment

physmodels.lib
=> fix some comments and values/ranges in physmodels

basics.lib, signals.lib
This version is much more readable and gives much smaller and clearer
block-diagrams.
It also doesn't have the limitation that maxN needs to be a power of 2.
=> rewrite slidingReduce

analyzers.lib
Time-domain adaptive algorithms for pitch-tracking and spectral centroid computation.
=> time-domain pitch-tracking and spectral centroid functions

quantizers.lib
It solves a bug in the lower frequencies.
@rmichon @sletz
=> Bigger table size for tabulate

basics.lib
Minor correction in documentation text.
=> Fix copy/paste text.

basics.lib
This adds a "curve" section feature to the break-point-function (`bpf`) library. Note that the `bias` value must be a compile-time constant. I'd like to find a way to improve that. Demo:
```faust
os = library("oscillators.lib");
it = library("interpolators.lib");
ba = library("basics.lib");
if = ba.if;
bpf = environment
{
// Start a break-point function
start(x0,y0) = \(x).(x0,y0,x,y0);
// Add a break-point
point(x1,y1) = \(x0,y0,x,y).(x1, y1, x, if(x < x0, y, if(x < x1, y0 + (x-x0)*(y1-y0)/(x1-x0), y1)));
// End a break-point function
end(x1,y1) = \(x0,y0,x,y).(if(x < x0, y, if(x < x1, y0 + (x-x0)*(y1-y0)/(x1-x0), y1)));
// Add a curve-point. `B` (compile-time constant) must be in range (0,1]
curve(B,x1,y1) = \(x0,y0,x,y).(x1, y1, x, if(x < x0, y, if(x < x1, _curve_util(x0,x1,y0,y1,B,x), …
```
=> add bpf curve functions

doc/docs/index.md
=> Fixed typo in index.md

oscillators.lib
Thanks @sletz and @magnetophon :)
=> Update oscillators doc to add note to use LF sawtooth fundamental for CZ waveforms

demos.lib, reverbs.lib
This is GPL v3 code. Since we're not making binaries or "marketing", I think it is appropriate to name the functions directly after Vital. https://github.com/mtytel/vital If you have concerns let me know.
=> add Vital reverb

filters.lib
Just doc edits, no code changes.
=> Edit docs for Kalman filter

reverbs.lib
This uses `ba.take` instead of `rdtable`.
=> Update Vital Reverb code style

filters.lib
I like this refactored but equivalent version of the Kalman filter more.
=> Refactor Kalman filter

filters.lib
This adds the 1€ Filter <https://gery.casiez.net/1euro/>.
Demo:
```faust
//-----------------`(fi.)oneEuro`----------------------------------
// The One Euro Filter (1€ Filter) is an adaptive lowpass filter.
// The input signal is smoothed according to an exponential
// moving average (EMA) whose alpha value is determined
// according to an EMA of the input's first-order derivative.
// This kind of filter is commonly used in object-tracking,
// not necessarily audio processing.
// 
// #### Usage
//
// ```
// _ : oneEuro(derivativeCutoff, beta, minCutoff) : _
// ```
//
// Where:
//
// * `derivativeCutoff`: Used to filter the first derivative of the input. 1 Hz is a good default.
// * `beta`: "Speed" parameter where higher values reduce latency. Range is [0-1].
// * …
```
=> add oneEuro filter

physmodels.lib
Simple example:
// Lotka-Volterra equations parameterized by a,b,c,d
LV(a,b,c,d, t,x,y) =
a*x - b*x*y,
c*x*y - d*y;
// solve using the fourth-order method
process = pm.rk_solve_4(
0.01,			// time step
LV(0.1,0.02,0.03,0.4),	// LV() with random parameters
(3,4)			// initial values
);
=> Add pm.rk_solve() function, Runge-Kutta solver

oscillators.lib
See https://ccrma.stanford.edu/STANM/stanms/stanm5/stanm5.pdf
=> Add os.dsf environment, oscsillators with exponentially decaying harmonics

vaeffects.lib
=> Add Vicanek's matched (decramped) second-order Butterworth low and high shelving filters.

noises.lib
As discussed on discord couple of weeks back, contributing the deterministic noise function
=> Deterministic noise function
